[package]
name = "gmpublisher"
version = "1.0.0"
description = "A Tauri App"
authors = [ "William Venner <william@venner.io>" ]
license = "GPL-3.0"
repository = "https://github.com/WilliamVenner/gmpublisher"
default-run = "gmpublisher"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
bindgen = "0.57.0"

[dependencies]
steamworks = { git = "https://github.com/WilliamVenner/steamworks-rs.git", branch = "master", features = [ "serde" ] }
byteorder = "1.4.2"
image = "0.23.13"
base64 = "0.13.0"
webview_official = "0.0.4"
steamlocate = "0.1.3"
anyhow = "1.0.38"
dirs = "3.0.1"
msgbox = "0.6.0"
opener = "0.4.1"
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive", "rc" ] }
tauri = { version = "0.11.1", features = [ "all-api" ] }
lazy_static = "1.4.0"
num_cpus = "1.13.0"
erased-serde = "0.3.13"
chardetng = "0.1.10"
sysinfo = "0.16.4"
dunce = "1.0.1"
thiserror = "1.0"
crossbeam = "0.8.0"
indexmap = "1.6.2"
backtrace = "0.3"

[target."cfg(windows)".build-dependencies]
winres = "0.1"

[features]
embedded-server = [ "tauri/embedded-server" ]
no-server = [ "tauri/no-server" ]

[[bin]]
name = "gmpublisher"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1 # does this work with lto = true?
