[package]
name = "gmpublisher"
version = "2.0.0"
description = "gmpublisher"
authors = [ "William Venner <william@venner.io>" ]
license = "GPL-3.0"
repository = "https://github.com/WilliamVenner/gmpublisher"
default-run = "gmpublisher"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
#tauri-build = { git = "https://github.com/tauri-apps/tauri", features = [ "codegen" ] }
tauri-build = { path = "../../tauri/core/tauri-build", features = [ "codegen" ] }
#tauri-build = { git = "https://github.com/williamvenner/tauri", features = [ "codegen" ], branch = "fix/slow_dev_builds" }
bindgen = "0.57.0"

[dependencies]
turbonone = { path = "../../turbonone" }
#tauri = { git = "https://github.com/tauri-apps/tauri", features = [ "api-all" ] }
tauri = { path = "../../tauri/tauri", features =["api-all"]}
#tauri = { git = "https://github.com/williamvenner/tauri", features =["api-all"], branch = "fix/slow_dev_builds" }
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive", "rc" ] }
steamworks = { git = "https://github.com/WilliamVenner/steamworks-rs.git", branch = "master", features = [ "serde" ] }
#steamworks = { path = "../../steamworks-rs", features = [ "serde" ] }
rayon = "1.5.0"
parking_lot = { version = "0.11", features = [ "serde" ] }
xz2 = "0.1.6"
indexmap = "1.6.2"
dunce = "1.0.1"
sysinfo = "0.16.4"
lazy_static = "1.4.0"
dirs = "3.0.1"
anyhow = "1.0.38"
image = "0.23.13"
base64 = "0.13.0"
rfd = "0.2.2"
atomic_refcell = "0.1.7"
thiserror = "1.0.24"
chardetng = "0.1.10"
byteorder = "1.4.3"
app_dirs = "1.2.1"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[profile.release]
lto = true
codegen_units = 1
